### ISSUE TITLE
Add `dig` binary to image to allow defining health probes

### ISSUE THREAD

**Issue by roobre** [klutchell/dnscrypt-proxy-docker#108]
Hi there!

I happen to run this image on my Kubernetes cluster. It has happened to me a couple times that, for reasons not related to this image, the deployment is not working as expected. While most of the time is due to networking issues, DNS issues are notoriously hard to debug (as the meme goes).

I think being able to define a readiness or health probe could help with this, as Kubernetes (or any other orchestration system) could notice right away that a container is not working as expected and flag it somewhere.

Unlike HTTP probes though, DNS probes are not supported by orchestration systems themselves, so we need to resort to probes that run a command and see if it exits with 0. This is, however, impossible with the current image, as it does not include any binary that can be used to check if `dnscrypt-proxy` is running as expected.

I propose that we add `dig` to the container image, so users can define a readiness probe like the following:
```yaml
readinessProbe:
  periodSeconds: 5
  failureThreshold: 2
  exec:
    command:
      - dig
      - google.com
      - "@127.0.0.1"
      - -p
      - "5353"
```

And therefore be notified when the container stops responding to queries.
